### ISSUE TITLE
Inflection not working

### ISSUE THREAD

**Issue by SmoothKen** [Lyroxide/yomichan-korean#10]
Hi, this is Brave Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit) on Linux

Everything seems to work fine except for inflection. For example, it only responds with "먹" given "먹어요". Multiple dictionaries/disabling Yomichan have been tried. What am I possibly missing here?

**Comment by Lyroxide** [comment]
I just download latest Brave Version 1.60.118 Chromium: 119.0.6045.163 (Official Build) (64-bit)
 on Windows and inflection is working for me.

Firstly, did you install my version of Yomichan? It is found [here](https://github.com/Lyroxide/yomichan-korean/releases/tag/1.2).

You should also mention what dictionaries you installed. Only [my dictionaries](https://drive.google.com/drive/u/1/folders/1YRw_FPSyGqKd8B0ubs8I36AAfbduWZnJ) work, and would only work in my version of Yomichan.

You could maybe try a different browser, or run Windows, though I don't think Linux is the issue here

**Comment by SmoothKen** [comment]
Ah, I see. Indeed I probably clicked into the old krdict. 

One small suggestion, it may be better to have shorter entries (like the one I attach). I also sort the sub-entries by stars.

Thank you for your hard work.

[term_bank_1.json](https://github.com/Lyroxide/yomichan-korean/files/13402491/term_bank_1.json)

**Comment by Lyroxide** [comment]
>it may be better to have shorter entries

Maybe, but as one becomes more advanced in the language, shorter entries do not make the cut.

>sort the sub-entries by stars

Other than the dictionary from KRDICT, which is a learner's dictionary, sorting words based on frequencies for homonym-heavy language like Korean is a very daunting task.
