### ISSUE TITLE
Scrolling and Popup Problem

### ISSUE THREAD

**Issue by huannv100** [Lyroxide/yomichan-korean#2]
I'm using Yomichan for Korean with Kiwi Browser on Android. It kind of works well, but there are some problems.

1. When I click a word, a window pops up showing its meanings in dictionaries. I scroll down to read meanings at the bottom, but somehow, it periodically scrolls back to the top (like every 10 seconds or so). Or maybe it opens a new window with the same word that I selected every 10 seconds or so.

2. Somehow, the child windows (popups inside popup) close too fast that I don't even have time to read them properly. Is there a setting for this?

**EDIT**: This is the record of the issues.  it automatically scrolled back to the top or opened a new one, but this occurred probably after more than 10 seconds.
https://streamable.com/yp5mkp

**Comment by ghost** [comment]
You could try to switch the pop up instance for native browser management, but it isn't guaranteed that it would work fine though, it would depend on the window management of your web-browser.

That is how you can do it

1. Toggle the advanced mode on youmichan
2. Go to Window Configuration
3. And mark toggle the option "Use a native browser window instead of an embedded popup" on.

![image](https://github.com/Lyroxide/yomichan-korean/assets/103891807/dde19696-f961-47ff-822e-44611ccd367f)

Good luck

**Comment by huannv100** [comment]
Thank you. 
That feature is new to me, and it does solve the issue. However, I still prefer pop-ups since opening in a new browser window and then going back is a bit slow and distracting for me.

**Comment by ghost** [comment]
Like i said i couldn't be sure because it depends on your web-browser, but you should be able to set the window style for pop up even with a native browser tab, try to set the window style for pop up, it may fix the problem.

you should have something similar to that

![image](https://github.com/Lyroxide/yomichan-korean/assets/103891807/f24aa494-71c4-49c4-ad0f-1fe9af1f1d51)

**Comment by huannv100** [comment]
I tried changing various window styles and delays, but it didn't work. I think the problem is related to the mobile version specifically. I also tried using Yandex browser, and the exact same issue occurred.

**Comment by Lyroxide** [comment]
This is not exactly an issue with Yomichan for Korean. I use Kiwi Browser too and never encountered any issues. Can you make sure you're on this particular version of Kiwi, which is the last version that supports zip installed extensions. https://github.com/kiwibrowser/src.next/releases/tag/4736345870

Anyway, try to use these settings:
Under Scanning → Configure advanced scanning inputs... add second input
Input types: Mouse
Search types: Both checked
Touch options: Scan on touch press
Pen options: Scan on pen press, Scan on pen move (while touched)
Uncheck the rest

**Comment by huannv100** [comment]
Hi, I downloaded Kiwi Browser from the Play Store, and it was the latest version available, which they had updated several days ago. However, I also just tried uninstalling it and downloaded the version from GitHub (arm64). I kept the same settings as before, but the same issues still happened.

I'm currently trying the settings you recommended, as they seem to work on your mobile. It's possible that the problem is specific to my device. If you don't mind, could you export your settings and upload them so that I don't miss anything?

**Comment by huannv100** [comment]
I think the problem is related to the krdict dictionaries. I tried some Chinese dictionaries, and they all work well and don't have any problems.
I tried installing it on a different phone, and the same exact problem occurred with the krdict dictionaries. When I select a word and the popup appears, if I scroll down to the bottom and let go, the dictionary automatically scrolls back up to the top after several seconds, or sometimes 10 seconds.

**Comment by Lyroxide** [comment]
When you mean trying Chinese dictionaries, do you mean using my fork of Yomichan, disabling Korean but enabling Chinese dictionaries?

This is not a problem I could replicate in my device, so I don't know how to help. My settings are mostly default too. You could try reducing 'Maximum number of results' and 'Text scan length', and see if that changes anything, because conversion of hangul back and forth could take some resources if your device isn't that powerful.

**Comment by huannv100** [comment]
I used a Chinese dictionary from this source (Chinese-Chinese or Chinese-English dictionaries) and tested them one by one by enabling one dictionary at a time. 
You can find the dictionaries here: https://drive.google.com/drive/folders/1-WReUZvneHEkvnjeqJA4oT08od7eK-sq

I tried the krdict dictionaries in your fork (KR-EN and monolingual Korean) and both have the same issue.
I have already set both the 'Maximum number of results' and 'Text scan length' to 8, but the problem persists.
I am using a Galaxy Note 10 Plus, and in my experience, I find it to be a fast and reliable phone.

**Comment by Lyroxide** [comment]
No problem on my device and Kiwi browser, so I can't help :/

**Comment by huannv100** [comment]
That's strange. I tried on two different phones, and the same problem happens. Is there any way I can debug the issue?

**Comment by huannv100** [comment]
I think I may have found some clues regarding the issue. After examining the error report from the extension, I came across the following details. I did check other sites as well, but it seems that the problem is specific to this particular site.
The problem occurs specifically with the YTN site, whereas it works perfectly fine with the "Humans of Seoul" site.

https://www.ytn.co.kr/
https://humansofseoul.com/

![image](https://github.com/Lyroxide/yomichan-korean/assets/49158530/4337458f-d69f-4665-9bc0-3d739f2e4f41)
