### ISSUE TITLE
Pop/up on Kiwi Browser android doesn't work on local files

### ISSUE THREAD

**Issue by Musrar** [Lyroxide/yomichan-korean#8]
Many thanks for this fork. I tried on my android phone with kiwi browser and while for webpages it works perfectly, the scanning on local files I open through kiwi browser doesn't work. It depends on the file type or is it just not possible at all? The option "Allow acces to files URL" is checked on.

Kiwi Browser (Chrome), Android 10

Yomichan version: 22.10.23.0

**Comment by Lyroxide** [comment]
If you're trying to open a pdf, then using an online pdf reader should make yomichan work

https://mozilla.github.io/pdf.js/web/viewer.html

As for epubs, you can use https://github.com/ttu-ttu/ebook-reader

Otherwise, I do not add features to yomichan that is not for Korean. Direct your question to Yomitan instead
